// Generated by sir sloppy viberton himself (copilot)
package com.github.ldavid432.contextualcursor.serialization.adapters;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonNull;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import lombok.Singular;
import lombok.Value;

/**
 * TypeAdapterFactory that:
 * - Omits a field during serialization if its serialized JsonElement exactly equals the explicitly supplied default.
 * - Prefills a missing field during deserialization with the explicitly supplied default JsonElement.
 * <p>
 * Differences from earlier versions:
 * - When serializing/deserializing instances of a subclass, defaults registered for a superclass or interface
 * will be found and applied to the subclass.
 * - Defaults are still computed lazily and disabled for a class if computing them via the real Gson causes
 * re-entrancy (IllegalStateException / StackOverflowError).
 */
public final class SkipFieldDefaultsTypeAdapterFactory implements TypeAdapterFactory
{

	@Value
	@lombok.Builder
	public static class FieldDefault
	{
		Class<?> parentClass;
		String jsonFieldName;
		Object defaultValue;
	}

	// raw defaults grouped by the declaring parent class (jsonFieldName -> raw default Object)
	private final Map<Class<?>, Map<String, Object>> rawDefaultsByClass = new HashMap<>();

	// cache of computed JsonElements per requested runtime class.
	// We cache per-requested-class so lookups are fast; entries can be shared when multiple runtime
	// classes map back to the same declaring class defaults.
	// Class -> (jsonFieldName -> JsonElement)
	private final ConcurrentHashMap<Class<?>, Map<String, JsonElement>> jsonDefaultsByClass = new ConcurrentHashMap<>();

	private SkipFieldDefaultsTypeAdapterFactory(List<FieldDefault> fieldDefaults)
	{
		List<FieldDefault> fieldDefaults1 = fieldDefaults != null ? Collections.unmodifiableList(new ArrayList<>(fieldDefaults)) : Collections.emptyList();
		for (FieldDefault fd : fieldDefaults1)
		{
			rawDefaultsByClass.computeIfAbsent(fd.getParentClass(), c -> new HashMap<>()).put(fd.getJsonFieldName(), fd.getDefaultValue());
		}
	}

	public static Builder builder()
	{
		return new Builder();
	}

	public static final class Builder
	{
		@Singular("fieldDefault")
		private final List<FieldDefault> fieldDefaults = new ArrayList<>();

		public Builder add(Class<?> parentClass, String jsonFieldName, Object defaultValue)
		{
			this.fieldDefaults.add(FieldDefault.builder().parentClass(parentClass).jsonFieldName(jsonFieldName).defaultValue(defaultValue).build());
			return this;
		}

		public SkipFieldDefaultsTypeAdapterFactory build()
		{
			return new SkipFieldDefaultsTypeAdapterFactory(fieldDefaults);
		}
	}

	/**
	 * Find a declaring class in rawDefaultsByClass for the supplied runtime class.
	 * Search order: the runtime class itself, then its interfaces (recursively), then its superclass chain
	 * (and their interfaces), returning the first class/interface that has registered raw defaults.
	 * <p>
	 * Returns null if no registered defaults are found anywhere in the hierarchy.
	 */
	private Class<?> findSourceClassWithRawDefaults(Class<?> runtimeClass)
	{
		if (runtimeClass == null)
		{
			return null;
		}

		// first, walk up the class chain; for each class check itself and its interfaces
		Class<?> cls = runtimeClass;
		while (cls != null)
		{
			if (rawDefaultsByClass.containsKey(cls))
			{
				return cls;
			}
			Class<?> iface = findInInterfacesWithDefaults(cls.getInterfaces());
			if (iface != null)
			{
				return iface;
			}
			cls = cls.getSuperclass();
		}
		return null;
	}

	private Class<?> findInInterfacesWithDefaults(Class<?>[] ifaces)
	{
		for (Class<?> i : ifaces)
		{
			if (rawDefaultsByClass.containsKey(i))
			{
				return i;
			}
			Class<?> nested = findInInterfacesWithDefaults(i.getInterfaces());
			if (nested != null)
			{
				return nested;
			}
		}
		return null;
	}

	/**
	 * Compute and cache JsonElement defaults for the requesting runtime class.
	 * This will locate the declaring source class (could be a superclass or interface),
	 * compute JsonElements for that source class's raw defaults using the supplied Gson, and
	 * cache the resulting map under the requesting runtime class for future fast lookup.
	 * <p>
	 * If conversion of any default via the provided Gson fails due to re-entrancy (IllegalStateException
	 * or StackOverflowError), defaults for the requesting runtime class are disabled (an empty map is cached).
	 */
	private Map<String, JsonElement> computeJsonDefaultsIfAbsent(Gson gson, Class<?> runtimeClass)
	{
		Map<String, JsonElement> existing = jsonDefaultsByClass.get(runtimeClass);
		if (existing != null)
		{
			return existing;
		}

		synchronized (jsonDefaultsByClass)
		{
			existing = jsonDefaultsByClass.get(runtimeClass);
			if (existing != null)
			{
				return existing;
			}

			// find the source class (declaring class) that has raw defaults
			Class<?> sourceClass = findSourceClassWithRawDefaults(runtimeClass);
			if (sourceClass == null)
			{
				Map<String, JsonElement> empty = Collections.emptyMap();
				jsonDefaultsByClass.put(runtimeClass, empty);
				return empty;
			}

			// If we've already computed for the sourceClass, reuse it and cache under runtimeClass
			Map<String, JsonElement> sourceCached = jsonDefaultsByClass.get(sourceClass);
			if (sourceCached != null)
			{
				jsonDefaultsByClass.put(runtimeClass, sourceCached);
				return sourceCached;
			}

			Map<String, Object> rawMap = rawDefaultsByClass.get(sourceClass);
			if (rawMap == null || rawMap.isEmpty())
			{
				Map<String, JsonElement> empty = Collections.emptyMap();
				jsonDefaultsByClass.put(sourceClass, empty);
				jsonDefaultsByClass.put(runtimeClass, empty);
				return empty;
			}

			Map<String, JsonElement> result = new HashMap<>(rawMap.size());
			try
			{
				for (Map.Entry<String, Object> e : rawMap.entrySet())
				{
					String prop = e.getKey();
					Object rawDefault = e.getValue();
					JsonElement je;
					if (rawDefault == null)
					{
						je = JsonNull.INSTANCE;
					}
					else
					{
						// Use the caller's Gson to serialize the provided default (respects adapters).
						// If this throws due to adapter construction re-entrancy, we disable defaults for the class.
						je = gson.toJsonTree(rawDefault);
					}
					result.put(prop, je);
				}
			}
			catch (IllegalStateException | StackOverflowError ex)
			{
				// Can't safely compute defaults for this class with the current Gson (likely re-entrancy).
				Map<String, JsonElement> empty = Collections.emptyMap();
				jsonDefaultsByClass.put(sourceClass, empty);
				jsonDefaultsByClass.put(runtimeClass, empty);
				return empty;
			}
			catch (RuntimeException ex)
			{
				// Unexpected error serializing a default — treat those entries conservatively as JsonNull and continue.
				for (Map.Entry<String, Object> e : rawMap.entrySet())
				{
					result.putIfAbsent(e.getKey(), JsonNull.INSTANCE);
				}
			}

			Map<String, JsonElement> unmodifiable = Collections.unmodifiableMap(result);
			jsonDefaultsByClass.put(sourceClass, unmodifiable);
			jsonDefaultsByClass.put(runtimeClass, unmodifiable);
			return unmodifiable;
		}
	}

	@Override
	public <T> TypeAdapter<T> create(final Gson gson, final TypeToken<T> typeToken)
	{
		final Class<? super T> runtimeRaw = typeToken.getRawType();

		final TypeAdapter<T> delegate = gson.getDelegateAdapter(this, typeToken);
		final TypeAdapter<JsonElement> jsonElementAdapter = gson.getAdapter(JsonElement.class);

		return new TypeAdapter<T>()
		{
			@Override
			public void write(JsonWriter out, T value) throws IOException
			{
				if (value == null)
				{
					out.nullValue();
					return;
				}

				// Lazily compute any defaults for this runtime class or its supertypes/interfaces
				Map<String, JsonElement> classDefaults = computeJsonDefaultsIfAbsent(gson, runtimeRaw);

				// If no defaults are configured for this runtime class or any of its supertypes, delegate directly
				if (classDefaults == null || classDefaults.isEmpty())
				{
					delegate.write(out, value);
					return;
				}

				// Get the full serialized JSON tree for the value (respects registered adapters)
				JsonElement actualTree = delegate.toJsonTree(value);
				if (actualTree == null || !actualTree.isJsonObject())
				{
					delegate.write(out, value);
					return;
				}

				JsonObject actualObj = actualTree.getAsJsonObject();

				// Remove properties that exactly equal the supplied default JsonElement
				Iterator<Map.Entry<String, JsonElement>> it = actualObj.entrySet().iterator();
				while (it.hasNext())
				{
					Map.Entry<String, JsonElement> entry = it.next();
					String propName = entry.getKey();
					JsonElement def = classDefaults.get(propName);
					if (def != null && def.equals(entry.getValue()))
					{
						it.remove();
					}
				}

				jsonElementAdapter.write(out, actualObj);
			}

			@Override
			public T read(JsonReader in) throws IOException
			{
				// Lazily compute any defaults for this runtime class or its supertypes/interfaces
				Map<String, JsonElement> classDefaults = computeJsonDefaultsIfAbsent(gson, runtimeRaw);

				// If no defaults are configured for this runtime class or any of its supertypes, delegate directly
				if (classDefaults == null || classDefaults.isEmpty())
				{
					return delegate.read(in);
				}

				// Read incoming JSON as element
				JsonElement incoming = jsonElementAdapter.read(in);

				if (incoming == null || incoming.isJsonNull())
				{
					return delegate.fromJsonTree(incoming);
				}

				if (!incoming.isJsonObject())
				{
					return delegate.fromJsonTree(incoming);
				}

				JsonObject incomingObj = incoming.getAsJsonObject();

				// Insert defaults for keys that are missing (do not override present keys, even if JsonNull)
				for (Map.Entry<String, JsonElement> d : classDefaults.entrySet())
				{
					String prop = d.getKey();
					if (!incomingObj.has(prop))
					{
						incomingObj.add(prop, d.getValue().deepCopy());
					}
				}

				return delegate.fromJsonTree(incomingObj);
			}
		};
	}
}
